name: Formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            config/requirements_dev.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install black
        run: |
          pip install black==22.6.0
          pip install black[jupyter]

      - name: Format with black
        run: |
          black . --line-length 94 --diff --check
