name: Update contributors

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            config/requirements_dev.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r config/requirements_dev.txt

      - name: Update README.md with new contributors
        run: |
          # Get the list of files changed in the last commit
          files=$( git diff --name-only HEAD HEAD^1)

          # Iterate over each file
          for file in $files
          do
              # Get the author of the last commit that changed the file
              author=$(git log -1 --pretty=format:'%an' -- $file)

              # Run the update_contributors.py script with the file and author as arguments
              python .github/scripts/update_contributors.py -f $file -a "$author"
          done

      - name: Commit and Push changes to repo
        run: |
          chmod +x .github/scripts/push_update.sh
          .github/scripts/push_update.sh
        shell: bash
