name: Daily Problem Update

on:
  workflow_dispatch:
    inputs:
      chosen_day:
        description: "Choose a day of the month to update the problem description for."
        required: false
  schedule:
    - cron: "15 6 * * *" # Runs every day at 7:15 AM UTC+1

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            config/requirements_dev.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r config/requirements_dev.txt

      - name: Get Target day
        run: |
          if [ -z "${{ github.event.inputs.chosen_day }}" ]; then
            chosen_day=$(date +'%d')
            echo "Chosen day (defaulting to current day): $chosen_day"
          else
            chosen_day=${{ github.event.inputs.chosen_day }}
            echo "Chosen day of the month: $chosen_day"
          fi

      - name: Update Problem description for the day
        run: |
          python .github/scripts/update_description.py -d $chosen_day
          echo "Updated Problem description for the day: $chosen_day"

      - name: Commit and Push changes to repo
        run: |
          chmod +x .github/scripts/push_update.sh
          .github/scripts/push_update.sh
        shell: bash
